name: typewriter
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Jonah Williams <jonahwilliams@google.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  analyzer:
  quiver:
  source_gen:
  build_runner:
  yaml:
  xml: 2.5.0
  code_builder: 1.0.0-beta+3

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  mockito:
